Repository boolsazo/bank-challenger, pull requests merged in 2023-05, with the labels that each got.

#2 DOCS: Update README.md
  README.md
Labels: documentation

#6 FEAT: JPA Repository Unit Test
  pom.xml
  src/main/java/com/boolsazo/bankchall/domain/Account.java
  src/main/java/com/boolsazo/bankchall/domain/AccountRule.java
  src/main/java/com/boolsazo/bankchall/domain/Goal.java
  src/main/java/com/boolsazo/bankchall/domain/Rule.java
  src/main/java/com/boolsazo/bankchall/domain/SavingHistory.java
  src/main/java/com/boolsazo/bankchall/domain/Survey.java
  src/main/java/com/boolsazo/bankchall/domain/User.java
  src/main/java/com/boolsazo/bankchall/repository/AccountRepository.java
  src/main/java/com/boolsazo/bankchall/service/AccountService.java
  src/main/java/com/boolsazo/bankchall/service/impl/AccountServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/boolsazo/bankchall/MyBatisFrameworkUnitTest.java
  src/test/java/com/boolsazo/bankchall/repository/AccountRepositoryTest.java
Labels: enhancement

#7 FIX: 테이블 구조 수정 및 불필요한 파일 삭제
  src/main/java/com/boolsazo/bankchall/common/BaseTimeEntity.java
  src/main/java/com/boolsazo/bankchall/domain/Account.java
  src/main/java/com/boolsazo/bankchall/domain/AccountRule.java
  src/main/java/com/boolsazo/bankchall/domain/Goal.java
  src/main/java/com/boolsazo/bankchall/domain/GoalAccount.java
  src/main/java/com/boolsazo/bankchall/domain/GoalAccountPK.java
  src/main/java/com/boolsazo/bankchall/domain/Rule.java
  src/main/java/com/boolsazo/bankchall/domain/SavingHistory.java
  src/main/java/com/boolsazo/bankchall/domain/Survey.java
  src/main/java/com/boolsazo/bankchall/domain/TestObject.java
  src/main/java/com/boolsazo/bankchall/domain/User.java
  src/main/java/com/boolsazo/bankchall/service/impl/AccountServiceImpl.java
  src/main/java/com/boolsazo/bankchall/test/TestUtil.java
  src/main/resources/config/SqlMapConfig.xml
  src/main/resources/config/dbconn.properties
  src/main/resources/mapper/test.xml
  src/test/java/com/boolsazo/bankchall/MyBatisFrameworkUnitTest.java
Labels: invalid

#10 Feat: Create query related to user
  src/main/java/com/boolsazo/bankchall/controller/UserController.java
  src/main/java/com/boolsazo/bankchall/domain/User.java
  src/main/java/com/boolsazo/bankchall/repository/UserRepository.java
  src/main/java/com/boolsazo/bankchall/service/UserService.java
  src/main/java/com/boolsazo/bankchall/service/impl/UserServiceImpl.java
Labels: enhancement

#19 FIX: Long -> int로 수정
  src/main/java/com/boolsazo/bankchall/controller/WithdrawAccountController.java
  src/main/java/com/boolsazo/bankchall/domain/Account.java
  src/main/java/com/boolsazo/bankchall/domain/Goal.java
  src/main/java/com/boolsazo/bankchall/domain/GoalAccount.java
  src/main/java/com/boolsazo/bankchall/domain/GoalAccountPK.java
  src/main/java/com/boolsazo/bankchall/domain/User.java
  src/main/java/com/boolsazo/bankchall/dto/AccountResponse.java
  src/main/java/com/boolsazo/bankchall/dto/WithdrawRegisterRequest.java
  src/main/java/com/boolsazo/bankchall/repository/AccountRepository.java
  src/main/java/com/boolsazo/bankchall/repository/GoalRepository.java
  src/main/java/com/boolsazo/bankchall/repository/UserRepository.java
  src/main/java/com/boolsazo/bankchall/service/AccountService.java
  src/main/java/com/boolsazo/bankchall/service/GoalService.java
  src/main/java/com/boolsazo/bankchall/service/UserService.java
  src/main/java/com/boolsazo/bankchall/service/WithdrawAccountService.java
  src/main/java/com/boolsazo/bankchall/service/impl/AccountServiceImpl.java
  src/main/java/com/boolsazo/bankchall/service/impl/BFRServiceImpl.java
  src/main/java/com/boolsazo/bankchall/service/impl/GoalServiceImpl.java
  src/main/java/com/boolsazo/bankchall/service/impl/UserServiceImpl.java
  src/main/java/com/boolsazo/bankchall/service/impl/WithdrawAccountServiceImpl.java
  src/test/java/com/boolsazo/bankchall/repository/AccountRepositoryTest.java
Labels: bug

#20 FEAT: Show user information
  frontend/src/App.js
  frontend/src/pages/Main.js
  frontend/src/pages/User.js
  src/main/java/com/boolsazo/bankchall/controller/HelloController.java
  src/main/java/com/boolsazo/bankchall/controller/StatusController.java
  src/main/java/com/boolsazo/bankchall/controller/UserController.java
Labels: enhancement

#23 FEAT: Delete user
  README.md
  frontend/src/App.js
  frontend/src/index.js
  frontend/src/pages/Delete.js
  frontend/src/pages/Main.js
  frontend/src/pages/User.js
  src/main/java/com/boolsazo/bankchall/controller/HelloController.java
  src/main/java/com/boolsazo/bankchall/controller/StatusController.java
Labels: enhancement, invalid

#31 Fix: Update gitignore
  .gitignore
Labels: bug

#37 Feat: Add Survey page
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/pages/Survey.js
Labels: enhancement

#46 Feat: Submit survey
  frontend/src/pages/Survey.js
  src/main/java/com/boolsazo/bankchall/controller/SurveyController.java
Labels: enhancement

#53 Feat: Update user information api
  frontend/src/pages/Main.js
  frontend/src/pages/User.js
  src/main/java/com/boolsazo/bankchall/controller/StatusController.java
  src/main/java/com/boolsazo/bankchall/domain/Goal.java
  src/main/java/com/boolsazo/bankchall/dto/UserResponse.java
Labels: enhancement

#57 Feat: Add Storage Session
  frontend/src/App.js
  frontend/src/pages/Delete.js
  frontend/src/pages/Main.js
  frontend/src/pages/Survey.js
  frontend/src/pages/User.js
Labels: enhancement

#62 Feat: Update Button
  frontend/src/assets/img/icons/common/btn_login_naver.png
  frontend/src/components/Navbars/DemoNavbar.js
  frontend/src/pages/IndexSections/Hero.js
  frontend/src/pages/Survey.js
Labels: enhancement

#63 Feat: Update redirect link
  frontend/src/pages/Survey.js
Labels: enhancement
